### ISSUE TITLE
Add text to uploads

### ISSUE THREAD

**Issue by djensenius** [housing-stories/web#29]
We want to have a brief text description added to each sound. 

Question for @zeaufoucault 

Do we want users to add their own descriptions, or would we want this added after the sounds are uploaded by an administrative account?

**Comment by zeaufoucault** [comment]
oh David, i am sorry. i had not seen this email of yours. i expected to communicate with you on claudeallabouthome@gmail.com. anyway. here i am now. 

my answer: we would like the sound broadcasters to add their own descriptions.
